[package]
name = "particle_life_rust"
version = "0.2.0"
edition = "2021"


[dependencies]
bevy = { version = "0.15.2", features = ["dynamic_linking"] }
bevy_egui = "0.33.0"


[lib]
crate-type = ["cdylib", "rlib"]